### ISSUE TITLE
Issue on KissCartoon

### ISSUE THREAD

**Issue by meyerovb** [KarthikMAM/Kissanime-Download-Links-Grabber#2]
http://kisscartoon.me/Cartoon/Sofia-the-First-Season-01/Episode-001-Just-One-of-the-Princes?id=19363

Asked me for quality, said 0 was max.  I tried blank, 0, 1, always says "Sorry, but you have selected a quality that is not avilable"

**Comment by KarthikMAM** [comment]
The kisscartoon site has been updated and now they are encrypting the urls. So, I need to make some changes to the download logic in the extension. This will be fixed soon. Thank you for using my extension.

**Comment by meyerovb** [comment]
Thanks, I'm getting carpal tunnel trying to fill up a usb for my kid :)

**Comment by meyerovb** [comment]
U need to switch to these in background.js
`chrome.tabs.executeScript({ file: "Scripts/kisscartoon-aes.js" });
chrome.tabs.executeScript({ file: "Scripts/kisscartoon-sha256.min.js" });
chrome.tabs.executeScript({ file: "Scripts/kisscartoon-kissenc.min.js" });`

Switch asp.wrap to $kissenc.decrypt

They expanded their page reload interval human check, i upped the settimeout from 1200 to 12000 and it worked fine.  You may want to play with it till u hit the sweet spot.  Update: i think they verify after every 50 page loads as well... maybe when the error is thrown just show all the links processed so far, so at least you don't lose your progress.  then if you run the plugin from the nth video it will only process from that video forward, so you can restart.

Oh and a feature request, if the quality entered is > the available links, just select the last link.  I always want lowest quality, but if one page has 3 links and another has 4 links then it doesn't work.

And you may wanna be clearer when asking what 'quality' people want, i had to look at the code to understand what u were asking for.

**Comment by meyerovb** [comment]
And thank you, thank you so much!
